AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CodePipeline for Lambda

Resources:
  lambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: simplefunction.handler
      CodeUri: lambdafunction/
      Runtime: python3.8
      AutoPublishAlias: live
      Description: pyconf hydpy demo function
      MemorySize: 128
      Timeout: 10
      Tracing: Active
      Events:
        simpleApi:
          Type: Api
          Properties:
            Path: /
            Method: get