AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: CodePipeline for Lambda

Resources:
  lambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: simplefunction.handler
      CodeUri: lambdafunction/
      Runtime: python3.8
      AutoPublishAlias: live
      Description: Simple demo function
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/codeguru_profiler_lambda_exec
          AWS_CODEGURU_PROFILER_GROUP_NAME: test
          AWS_CODEGURU_PROFILER_TARGET_REGION: eu-central-1
      MemorySize: 128
      Timeout: 10
      Tracing: Active
      Events:
        simpleApi:
          Type: Api
          Properties:
            Path: /
            Method: get