AWSTemplateFormatVersion: "2010-09-09"
Description: Setup CodeBuild and CodeDeploy pipeline

Resources:

  artifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  lambdaArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  eventRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - events.amazonaws.com
            Action:
            - sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: eventpolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'codepipeline:StartPipelineExecution'
                Resource: !Join
                  - ':'
                  - - 'arn:aws:codepipeline'
                    - Fn::Sub: ${AWS::Region}
                    - Fn::Sub: ${AWS::AccountId}
                    - Ref: lambdaPipeline

  lambdaBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codebuild.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: lambdaBuildPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
          Version: '2012-10-17'

  lambdaDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codedeploy.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: '/'
      Policies:
      - PolicyName: lambdaDeployPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: '*'
            Resource: '*'
          Version: '2012-10-17'

  lambdaPipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - codepipeline.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: lambdaPipelinePolicy
        PolicyDocument:
          Statement:
          - Action:
            - codebuild:*
            - codecommit:*
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:GetObject
            - s3:GetObjectVersion
            - s3:GetBucketVersioning
            Resource: "*"
            Effect: Allow
          - Action:
            - s3:PutObject
            Resource:
            - arn:aws:s3:::codepipeline*
            Effect: Allow
          - Action:
            - s3:*
            - cloudformation:*
            - iam:PassRole
            Resource: "*"
            Effect: Allow
          Version: '2012-10-17'

  lambdaPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      RoleArn: !GetAtt lambdaPipelineRole.Arn
      Stages:
        - Name: Source
          Actions:
          - InputArtifacts: []
            Name: GetSource
            ActionTypeId:
              Category: Source
              Owner: AWS
              Version: 1
              Provider: CodeCommit
            OutputArtifacts:
            - Name: lambdaSourceOutput
            Configuration:
              RepositoryName: pyconf_hydpy
              BranchName: master
              PollForSourceChanges: false
            RunOrder: 1

        - Name: Tests
          Actions:
          - Name: LambdaTests
            ActionTypeId:
              Category: Test
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            InputArtifacts:
            - Name: lambdaSourceOutput
            OutputArtifacts:
            - Name: lambdaTestedOutput
            RunOrder: 1
            Configuration:
              ProjectName: !Ref lambdaTest
        
        - Name: Build
          Actions:
          - Name: LambdaBuild
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: 1
              Provider: CodeBuild
            InputArtifacts:
            - Name: lambdaSourceOutput
            OutputArtifacts:
            - Name: lambdaBuildOutput
            RunOrder: 1
            Configuration:
              ProjectName: !Ref lambdaBuild

        # - Name: Deploy
        #   Actions:
        #   - Name: LmbdaDeploy
        #     ActionTypeId:
        #       Category: Deploy
        #       Owner: AWS
        #       Version: '1'
        #       Provider: Lambda
        #     InputArtifacts: 
        #     - Name: lambdaTestedOutput
        #     OutputArtifacts:
        #     - Name: lambdaDeployOutput
        #     Configuration:
        #       ProjectName: !Ref lambdaDeploy
        #     RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Ref artifactsBucket

  lambdaTest:
    Type: AWS::CodeBuild::Project
    DependsOn: lambdaBuildRole
    Properties:
      Name: lambdaPipeline_Tests
      Description: Tests
      ServiceRole: !GetAtt lambdaBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            shell: bash
          phases:
            install:
              runtime-versions:
                python: 3.8
              commands:
                - echo Starting Install stage on $(date)
                - pip install pytest pytest-cov
            build:
              commands:
                - echo Execute tests  on $(date)
                - pytest tests/tests_lambda.py -vv --junit-xml=reports/unit.xml --cov=. --cov-report=xml
                - mkdir coverage
                - cp coverage.xml coverage/
            post_build:
              commands:
                - echo Execute post-build  on $(date)
          reports:
            lambdaTestUnit:
              files:
                - '**/*'
              base-directory: 'reports'
              discard-paths: false
              file-format: JUNITXML
            lambdaTestCoverage:
              files:
                - '**/*'
              base-directory: 'coverage'
              discard-paths: false
              file-format: COBERTURAXML
      TimeoutInMinutes: 10

  lambdaBuild:
    Type: AWS::CodeBuild::Project
    DependsOn: lambdaBuildRole
    Properties:
      Name: lambdaPipeline_Build
      Description: Tests
      ServiceRole: !GetAtt lambdaBuildRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            shell: bash
          phases:
            install:
              runtime-versions:
                python: 3.8
              commands:
                - echo Starting Install stage on $(date)
            build:
              commands:
                - echo Execute build on $(date)
                - ls -al
                - !Sub aws cloudformation package --template-file template.yml --s3-bucket ${lambdaArtifactsBucket} --output-template-file outputTemplate.yml
            post_build:
              commands:
                - echo Execute post-build on $(date)
          artifacts:
            type: zip
              - template.yml
              - outputTemplate.yml
      TimeoutInMinutes: 10

  masterPushRepoEvent:
    Type: AWS::Events::Rule
    DependsOn: eventRole
    Properties:
      Description: Execute when push to master branch
      EventPattern:
        source:
          - aws.codecommit
        detail-type:
          - CodeCommit Repository State Change
        resources: 
          - 
            !Join
            - ':'
            - - 'arn:aws:codecommit'
              - Fn::Sub: ${AWS::Region}
              - Fn::Sub: ${AWS::AccountId}
              - 'pyconf_hydpy'
        detail:
          referenceType: 
            - branch
          referenceName:
            - master
      State: ENABLED
      Targets: 
        - 
          Arn:
            !Join
            - ':'
            - - 'arn:aws:codepipeline'
              - Fn::Sub: ${AWS::Region}
              - Fn::Sub: ${AWS::AccountId}
              - Ref: lambdaPipeline
          Id: masterPushRepoEvent
          RoleArn: !GetAtt eventRole.Arn